### ISSUE TITLE
Before 1.0

### ISSUE THREAD

**Issue by Nexela** [Afforess/Factorio-Stdlib#103]
- [x] Release Script - Build, tag, add to releases

- [x] changelog - Because I am a slacker

- [x] Removal of deprecated files, Because updating require paths is easy 

- [ ] Primer on area/position metatable usage

**Comment by Afforess** [comment]
Seriously? You ninja'd me.

**Comment by Nexela** [comment]
Super fast!

**Comment by Afforess** [comment]
I'd also comment that there is no real need to keep deprecated files because:
1.) We have archived tags of old releases
2.) Nothing stops develops from staying on an old release if they think that version was good enough.

Mostly the important part is that we:
1.) Follow semver (MAJOR.MINOR.PATCH) - major versions only contain breaking api changes. 
2.) Document deprecations and broken apis

And if most releases end up being majors due to API changes...so be it.
