### ISSUE TITLE
Time of Day Events (Hour changes, Sunset, Sunrise, etc)

### ISSUE THREAD

**Issue by Afforess** [Afforess/Factorio-Stdlib#12]
Suggestion from forums: https://forums.factorio.com/viewtopic.php?f=96&t=23181&p=158743#p158352

**Comment by credomane** [comment]
I took a quick stab at this. What should we call sunrise and sunset? The exact time brightness leaves/reaches the darkest point or the exact time brightness leaves/reaches the max? Somewhere in the middle?

In my town sunset is currently 8:29PM but doesn't start getting dark until about 9:30pm then around 10pm it is completely dark. The same for sunrise. Sunrise is 6:24am but when I'm up for my daily walk at 6am it is already bright out.

**Comment by Afforess** [comment]
@credomane the events are for in-game time, not real life. So an event when the brightness starts increasing from 0.14 -> 1 would be the sunrise event, and the sunset event would be when brightness decreased from 1 -> 0.14.

**Comment by credomane** [comment]
I just finished posting an edit for what I did. I can adjust it to that if you want.

>I set the sunrise time to be about when the player flashlight clicks off and sunset for when it comes on.
I'll write some tests then push a PR for it to get looked over.

**Comment by Afforess** [comment]
Ah okay. Yeah your edit makes sense to me!

**Comment by credomane** [comment]
I really hate writing tests. I feel like right now I'm making the entire Factorio game world just to do a single test.

**Comment by Afforess** [comment]
@credomane you can generally get away with only making as many pieces of the game as you actually need. In this case, the script.on_event and a mock surface object is probably all you need.

**Comment by credomane** [comment]
> making as many pieces of the game as you actually need. 

Which seems like way more than it should be.
I have to build `remote.interfaces` to get the daytime from MoWeather if it exists as it likes to play with the surface daytime to simulate lightning as such.
Had to build 2 functions of `script` and a decent portion of `game`.

That was just to get the test running with out crashing due to a unknown function/table/whatever. Now I'm currently bashing my head against `Function was not called with the arguments`. Thanks busted. Now tell me what it *was* called with so I actually know what my problem is.

I know the issue is my failure in writing the test properly as while debugging the events fired on time every time inside Factorio. :(

Time to `myfile:write(serpent.dump(eventtable))` to the rescue. lol

**Comment by Afforess** [comment]
>I have to build remote.interfaces to get the daytime from MoWeather if it exists as it likes to play with the surface daytime to simulate lightning as such.

I am not sure this is needed, because Factorio 0.13 split the time of day and 'darkness' of a surface into two separate values. Changing the darkness no longer requires manipulating the time.

**Comment by credomane** [comment]
They did but darkness is marked read-only. Attempting to change it throws an error "LuaSurface::darkness is read-only." :(

I tried to maintain the most compatibility I could by polling MoWeather for the surface time if it is installed since LuaSurface.daytime becomes unreliable.

**Comment by Afforess** [comment]
Lame.
