### ISSUE TITLE
crash on 0.17.45

### ISSUE THREAD

**Issue by szentigrad3** [Afforess/Factorio-Stdlib#136]
https://puu.sh/DAGZm/be411242ef.jpg

**Comment by Nexela** [comment]
Please notice the very first line in the error message which states which mod is causing the issue.

The problem is with the upgrade builder and planner mode
line 899 in control.lua
 inventory = player.get_inventory(defines.inventory.player_trash)

There is no defines.inventory.player_trash  it was renamed to character_trash
Please report this to that mod author
