### ISSUE TITLE
Technology and recipe manupulation

### ISSUE THREAD

**Issue by mojo2012** [Afforess/Factorio-Stdlib#19]
Hi guys,

currently I'm doing stuff like this:

```
function addTechnologyUnlocksRecipe(technologyName, recipeName)
    data.raw["recipe"][recipeName].enabled = false
    if data.raw["technology"][technologyName].effects == nil then
        data.raw["technology"][technologyName].effects = {}
    end
    table.insert(data.raw["technology"][technologyName].effects,
        { type = "unlock-recipe", recipe = recipeName })
end
```

It would be nice if we'd have a Util class, that allows us to:
- add recipes to technologies
- add technologies
- enable/disable recipes/technologies etc

**Comment by Choumiko** [comment]
probably should become part of Data module (#9)

**Comment by Nexela** [comment]
Wonder if Bob (bobmods/boblibrary) Wouldn't mind some of his library functions being incorporated into STDLIB

**Comment by Afforess** [comment]
@Nexela the license for Bob's mod is not compatible:
https://forums.factorio.com/viewtopic.php?f=51&t=28573&sid=58ad28b3d2a4d83acef2d1fc2fcc125b
>License:
Since the old one seems to have gone missing... again... here is the liscence.

> * No Commercial Use - You are not allowed to make money off my work.
> * No Modification - Although I can't stop you from looking at my code, you are not allowed to distribute anything altered, or derived from my code without expressed permission first.
> * Distribution - You are allowed to redistribute my mods as is. This includes being repackaged as part of a mod pack.
> * Private Use - I am not impossing any limitations on private use, if you want to modify my work, or create your own using parts of mine, you are free to do so, as long as this altered or derived work does not become accessable to the public.

The first two items, No Commercial Use and No Modification both are incompatible with the stdlib license, which permits both commercial use, and modification. This could only be worked around if bobingabout gave explicit agreement to grant stdlib a license to use his code under our license.

_PS: This is why creative commons licenses are terrible for software development, they are incompatible with pretty much all FOSS licenses, because CC licenses are not actually FOSS, just "public source", not "open source"._

**Comment by OvermindDL1** [comment]
Easy enough to remake his library functions I'd wager.  I'm sure enough people have not looked at them yet that could black-box replicate them.

**Comment by Nexela** [comment]
Linking with #9
