### ISSUE TITLE
Area.to_xxx_area(entity) returns incorrect for rectangle bounding boxes in non N/S rotation

### ISSUE THREAD

**Issue by Nexela** [Afforess/Factorio-Stdlib#90]
![image](https://cloud.githubusercontent.com/assets/13972192/26738188/2eb15aae-479b-11e7-88ec-8a5aa2b41e6f.png)

Could also be in Position.add but don't have the time to look so making an issue as a reminder

This should return about -0.75

**Comment by Nexela** [comment]
Offset is only incorrect if height is > width

**Comment by Nexela** [comment]
Narrowed it down, Current solution, but not sure how much I like it.

--- Converts an entity and its selection_box to the area around it
-- @tparam LuaEntity entity to convert to an area
-- @treturn LuaBoundingBox
function Area.to_selection_area(entity)
    fail_if_missing(entity, "missing entity argument")

    local pos = entity.position
    local bb = entity.prototype.selection_box

    if entity.direction ~= defines.direction.north then
        return Area.rotate(Area.offset(bb, pos))
    end
    return Area.offset(bb, pos)
end

**Comment by Afforess** [comment]
Okay - I think I understand the issue here. The prototype definition is returning the generic bounding box, which apparently is defined for the N-S placement of the entity. Other directions result in the area being rotated 90 degrees, so that's what your check is doing. My only question is: Does the game ever return the direction as south (S-N orientation) and if so, then that should also be checked in your if statement, as N-S and S-N are isomorphic and should not result in rotation.

**Comment by Nexela** [comment]
Will be adjusting this some more tonight.

**Comment by Nexela** [comment]
Ok finally had to time check some 8 way rotations. will have the final fix pushed shortly :)
